### ISSUE TITLE
Information request: Rework interrupt dispatching

### ISSUE THREAD

**Issue by sy2002** [mist-devel/T65#1]
Hi @gyurco ,

Thank you for the great work that you are doing for MiST and MiSTer! I am a huge fan of your work and since I do not know how to reach you I thought I try this "information request" issue :-)

Your recent improvement of T65 "Rework interrupt dispatching" fixes an issue that was really a tough one for us to debug:
https://github.com/MiSTer-devel/C64_MiSTer/issues/141#issuecomment-1313690669

Again - thank you for that!

Now I am curious: Why did you do this fix? Where there more challenges that you discovered around the IRQ/NMI handling of the 6502 or was it specifically geared towards solving the All Hallow's Eve challenge?

Best regards,
  sy2002

**Comment by gyurco** [comment]
Hi,

First: the code was ugly, and the added fixes by me made it even more ugly
Second: it was buggy in some cases, like the mentioned demo

I tested the new one in many demos (where the interrupt delay was problematic even before, like Tsunami or Trick and Treat), and it also (still) passes the C64 Emulator Test Suite 2.15 IRQ and NMI tests.

**Comment by gyurco** [comment]
I close this, if you find any regressions, just reopen it.

**Comment by sy2002** [comment]
Thank you @gyurco for answering my question and for all the hard work you are doing. This was very helpful.
